## 开发配置文件
## @author <a href="https://github.com/xiaogithubooo">limou3434</a>
## @from <a href="https://datalearnhub.com">大数据工作室</a>
#
#server:
#  address: 192.168.101.254
#
#mybatis-plus:
#  configuration:
#    log-impl: '' # 关闭
#
#knife4j:
#  basic:
#    username: root
#    password: KNIFE4JWishuxue31415